name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main # Change this to your default branch
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      - name: Deploy in VPS
        run: |
          ssh -o StrictHostKeyChecking=no user@your-vps-ip "
            cd startingTranslatable && 
            git pull origin main && 
            cd server
            docker stack deploy -c ./docker-compose.yml translatable-server
          "
